// ? [key: path]: name
export enum EPageNames {
  dashboard = "Bảng điều khiển",
  products = "Sản phẩm",
  categories = "Danh mục",
  orders = "Đơn đặt hàng",
  customers = "Khách hàng",
  create = "Tạo mới",
  update = "Cập nhật",
  detail = "Chi tiết",
  roles = "Vai trò",
  permissions = "Quyền",
  brands = "Thương hiệu",
  colors = "Màu",
  voucherTypes = "Loại mã giảm giá",
  "user-genders" = "Giới tính người dùng",
  vouchers = "Mã giảm giá",
  sizes = "Kích cỡ",
  "payment-types" = "Loại thanh toán",
  "payment-statuses" = "Trạng thái thanh toán",
  "order-statuses" = "Trạng thái đơn hàng",
  accounts = "Tài khoản",
}
